### ISSUE TITLE
extensions.gnome.org extension page does not exist

### ISSUE THREAD

**Issue by Pant** [pgn674/TopIcons-plus-maintained#1]
I am navigating with Firefox at https://extensions.gnome.org/extension/1493/topicons-plus-maintained/ as mentioned at the README.md (commit: 3f5735a) but it says:

> 404 - Page not Found

**Comment by pgn674** [comment]
Oh, sorry, the extension status is still unreviewed, and I hadn't thought to check what the link looked like while I wasn't signed in. I'll update the readme appropriately.
